# Generated by Django 4.2.3 on 2023-07-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_alter_project_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
