# Generated by Django 4.2.3 on 2023-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_alter_project_first_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
