# Generated by Django 4.2.3 on 2023-07-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_project_checking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCheckDateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.project')),
            ],
        ),
    ]
